# Generated by Django 5.0.2 on 2024-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_remove_vistior_management_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistior_management',
            name='To_meet',
            field=models.CharField(choices=[('1', 'MD'), ('2', 'Manager')], default='1', max_length=15),
        ),
    ]
