# Generated by Django 5.0.2 on 2024-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_alter_vistior_management_to_meet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistior_management',
            old_name='Purpose_to_meet',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='vistior_management',
            old_name='Company_name',
            new_name='company_Name',
        ),
        migrations.RenameField(
            model_name='vistior_management',
            old_name='mobile_number',
            new_name='mobile_Number',
        ),
        migrations.RenameField(
            model_name='vistior_management',
            old_name='To_meet',
            new_name='to_Meet',
        ),
        migrations.RenameField(
            model_name='vistior_management',
            old_name='Visitor_name',
            new_name='visitor_Name',
        ),
        migrations.AddField(
            model_name='vistior_management',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
