# Generated by Django 5.0.2 on 2024-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_rename_purpose_to_meet_vistior_management_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistior_management',
            name='Reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
