# Generated by Django 5.0.2 on 2024-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_visitor_delete_vistior_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
