# Generated by Django 5.0.2 on 2024-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_capturedimage_delete_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='visitor_photos/')),
                ('designation', models.CharField(max_length=100)),
                ('person_to_meet', models.CharField(choices=[('MD', 'Managing Director'), ('Manager', 'Manager')], max_length=100)),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
