# Generated by Django 5.0.2 on 2024-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_alter_visitor_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(upload_to='visitor/'),
        ),
    ]
