# Generated by Django 5.0.2 on 2024-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_remove_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.FileField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
