# Generated by Django 5.0.2 on 2024-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0013_visitor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='person_to_meet',
            field=models.CharField(choices=[('MD', 'Managing Director'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
