# Generated by Django 5.0.2 on 2024-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0014_alter_visitor_company_name_alter_visitor_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(null=True, upload_to='visitor_photos'),
        ),
    ]
